/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "UART.h"
#include "com.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "PWM_3.h"
#include "PWM_4.h"
#include "PWM_5.h"
#include "Clock_1.h"
#include "F_1_aliases.h"
#include "F_1.h"
#include "F_2_aliases.h"
#include "F_2.h"
#include "F_3_aliases.h"
#include "F_3.h"
#include "F_4_aliases.h"
#include "F_4.h"
#include "F_5_aliases.h"
#include "F_5.h"
#include "PWM_6.h"
#include "F_6_aliases.h"
#include "F_6.h"
#include "PWM_7.h"
#include "F_7_aliases.h"
#include "F_7.h"
#include "PWM_8.h"
#include "F_8_aliases.h"
#include "F_8.h"
#include "PWM_9.h"
#include "F_9_aliases.h"
#include "F_9.h"
#include "ADC.h"
#include "POT1_aliases.h"
#include "POT1.h"
#include "POT2_aliases.h"
#include "POT2.h"
#include "POT3_aliases.h"
#include "POT3.h"
#include "POT4_aliases.h"
#include "POT4.h"
#include "POT5_aliases.h"
#include "POT5.h"
#include "MODE_aliases.h"
#include "MODE.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "UART_IntClock.h"
#include "ADC_SAR.h"
#include "ADC_IntClock.h"
#include "ADC_TempBuf_dma.h"
#include "ADC_FinalBuf_dma.h"
#include "ADC_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

